### ISSUE TITLE
Issue in cart screen (reflecting other items while increment/decrement counter of a perticular item in cart)

### ISSUE THREAD

**Issue by abdulchaman** [Lexodd-Hypernova/dresscode-ecom-#18]
Suppose you have multiple items present in the cart (Item A, Item B, Item C)
 and you want to increase/decrease the quantity of Item A,
while updating the counter of Item A, it also reflects the properties of Item B/ Item C. (property name: checked)
note: **checked** property reflecting
I want unchanged other items while updating a single particular item

**Comment by anuragchachan** [comment]
Noted.

**Comment by anuragchachan** [comment]
I tried to recreate the issue but there is no such reflection of other
properties (like checked ) and I also checked the code for updating
quantity on increment / decrement of counter, I didn't find any issue in
the code. Please check again & let me know if it occurs again please share
the screen recording, if possible.

Best Regards
Anurag Chachan

**Comment by abdulchaman** [comment]
the issue is fixed, the error was in the local state, whenever we update the checked property, it updates the cart in the local state. but updating the counter in the updateItemQuantity method takes the cart from the cartContext.

**Comment by anuragchachan** [comment]
ok.
